### ISSUE TITLE
HTML Editor Manager not loading and throwing critical error messages in DNN 9.2.1

### ISSUE THREAD

**Issue by dpuffenberger** [dnnsoftware/Dnn.Platform#2295]
## Description of bug
The HTML Editor Manager is not loading in the persona bar or on a standalone page in new or upgrade installations of 9.2.1.  Instead, trying to access the manager throws a critical error with details in the event log.  Doing a search for the stack trace led me to the original bug report that was listed in the old tracker. Apparently it was fixed in 9.2.0.

Original bug report: https://dnntracker.atlassian.net/browse/DNN-10575

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Settings > Site Settings > Site Behavior > More > HTML Editor Manager.
2. See error

## Current result
Error message.

## Expected result
Original function.

## Screenshots
https://user-images.githubusercontent.com/6980119/45191234-18cb5600-b210-11e8-8ab8-174361eedfa8.PNG

## Error log
Message: Object reference not set to an instance of an object.
StackTrace:
InnerMessage: Object reference not set to an instance of an object.
InnerStackTrace: 
at DNNConnect.CKEditorProvider.CKEditorOptions.BindUserGroupsGridView() at DNNConnect.CKEditorProvider.CKEditorOptions.Page_Load(Object sender, EventArgs e) at System.Web.UI.Control.OnLoad(EventArgs e) at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ ] 9.2.2
* [x] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by perezandres** [comment]
I'm having same issue and my HTML editor has been changed to a black skin:
![image](https://user-images.githubusercontent.com/6237180/45372537-864efc00-b5ed-11e8-8a81-64daf2c60ec1.png)

**Comment by perezandres** [comment]
My issue didn't show up just after upgrade or install, but randomly (apparently) in sometime. I still haven't been able to reproduce it in a consistent way, maybe is related with the later installation of some third-part module.

**Comment by meffj00** [comment]
We have done an upgrade from EVOQ 8 to DNN 9.2.1. The parent site gives the same error and also a black skin, but the several child sites are working perfect (no errors and a normal skin). 
Maybe this information will helps you to resolve the problem!

**Comment by valadas** [comment]
I can reproduce on Dnn 9.2.2 RC2 build 177 but it looks a bit different, the persona bar loads inside the persona bar container and under all that is the page with the error: 
![image](https://user-images.githubusercontent.com/6371568/45926073-bf8c4380-beec-11e8-8d11-f324dce72dee.png)

Nothing is logged in the website UI for logs, but in Portals/_default/logs I have this:

2018-09-23 04:50:26.249-04:00 [DanielValadasPC][D:6][T:59][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DNNConnect.CKEditorProvider.CKEditorOptions.BindUserGroupsGridView()
   at DNNConnect.CKEditorProvider.CKEditorOptions.Page_Load(Object sender, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2018-09-23 04:50:26.265-04:00 [DanielValadasPC][D:6][T:59][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=32&error=Object+reference+not+set+to+an+instance+of+an+object.&content=0
System.NullReferenceException: Object reference not set to an instance of an object.
   at DNNConnect.CKEditorProvider.CKEditorOptions.BindUserGroupsGridView()
   at DNNConnect.CKEditorProvider.CKEditorOptions.Page_Load(Object sender, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by OllyHodgson** [comment]
I've just tried a fresh isntall of DNN 9.2.2 RC2 build 177, and see the same symptoms as before. Fails with a critical error on first load. Worked on the second try. 

@valadas I couldn't reproduce the nested personabar :man_shrugging:

**Comment by valadas** [comment]
For the nested persona bar, it only happened if continuing to use the persona bar (other menu item) right after the first error. Refreshing the page fixes it.

**Comment by valadas** [comment]
Also, it is normal that this is not fixed by the latest RC because a fix was not yet made and merged on this release.

**Comment by perezandres** [comment]
I've upgraded from 9.2.0 to 9.2.2 (just released) and the issue seems to be fixed. Anyway, I still have to test it on other DNN 9 sites I'll have to upgrade. I'll tell you what happens ;-)

**Comment by dpuffenberger** [comment]
I just upgraded to 9.2.2.  Issue still exists.

**Comment by valadas** [comment]
Just upgraded a site from 9.1.1 to 9.2.2 release, issue did not reappear. Then installed a new 9.2.2 clean and also did not have the issue. For the record the 2 clean installs (first that showed the issue, and second that was fine) where on the same environment.
So either it was fixed by the final release or it is intermittent.

**Comment by js888** [comment]
Upgraded from 9.2.1 to 9.2.2 and the issue still persists. Anyone know of a temporary fix until a patch is released?

**Comment by justinacton** [comment]
Here is a solution.  I had this issue in 9.2.1 and 9.2.2.  This is what worked for me:

Of course make backups before doing any of this.

Run the following SQL script: delete from CKE_Settings where settingname like '%#skin%'
Now clear the cache from the Persona Bar > Settings > Servers

**Comment by birksy89** [comment]
I've just experienced this issue when taking a practically fresh install of DNN 9.2.0 (where this issue didn't exist) and then upgrading it to 9.2.2

I was about the follow @justinacton advice above - But before executing any SQL, I thought I'd just try clearing the cache.

This appears to have solved the problem, or like others have said - It's intermittent. 

I'll update this comment if it happens again.

**Comment by james7342** [comment]
Not sure if this is related or not. I was troubleshooting this on a site and found this interesting information in the web browser console indicating content was unable to display due to secure content. The site is SSL enabled and SSL enforced. If I turn off SSL the editor displays fine for me.
<img width="1058" alt="screenshot_09" src="https://user-images.githubusercontent.com/27960723/53890654-77b23200-3fdd-11e9-85bc-9396c14b9efd.png">

And maybe complete unrelated but I even though I can now get into CKEditor Settings they don't seem to safe to at least not applied to the editor. I can make changes for a page, site, module. press the save button and no error message is displayed during the process. Issue a SQL select * from CKE_Settings and I can see that the values appear to be updated. Go back in the edit settings and none of them are indicated. Then when using the editor on a site, page the changed aren't reflected either. 

Notice this message in the event log.
<img width="766" alt="screenshot_10" src="https://user-images.githubusercontent.com/27960723/53890994-38381580-3fde-11e9-8a7f-bf2132edcdb2.png">

So even though I can get to the editor now, the settings don't seem to get applied.

**Comment by valadas** [comment]
I was not able to reproduce any any version from after 9.2.2 up to 9.4.0, closing this for now, if you can still reproduce on 9.4.0 RC, please open a new issue.
