### ISSUE TITLE
Duplication of buttons in bottom bar in page edit mode (DNN 9.8.0)

### ISSUE THREAD

**Issue by lanthonyneville** [dnnsoftware/Dnn.Platform#4292]
# Description of bug

On entering page edit mode, the black bottom bar appears containing the usual buttons (Add Module, Add Existing Module, Page Settings, Close). However, each button is duplicated, so there are 8 buttons in total.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Log in as a super-user
2. Go to any page
3. Click on the Edit (pencil) button to enter page edit mode
4. The duplicated buttons appear

Note: in my installation, the duplication occurs on almost every page I edit. However on some occasions the buttons are not duplicated. I have not however seen a pattern in this.

## Expected behavior
The buttons should not be duplicated.

## Screenshots

![image](https://user-images.githubusercontent.com/22200046/98798379-bd0b4180-2405-11eb-8577-8acbfc8db0e3.png)

## Additional context
My installation was upgraded from DNN 9.6.1 to 9.8.0. Before 9.8.0 I had not seen any duplication of the edit buttons.

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.08.00 release
* [ ] 09.07.02 latest supported release

## Affected browser
(only able to test the below 3 browser types)
* [ ] Firefox
* [X] Chrome
* [ ] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
I have been using 9.8.0 since RC1 many many times an never had that issue. However I have seen it intermittently on other people machines in meetings.

It would be incredibly useful if someone experiencing it can actually spot what's different on the pages where it happens and does not happen... These are some shots in the dark guesses:

- Theme
- Containers
- Localization
- Modules on page
- Page permissions
- Different logged in user
- Something common in the urls
- Http vs Https
etc...

**Comment by valadas** [comment]
Looked at this a bit with @mitchelsellers and we could no longer reproduce on the same instance where it was happening... It may be a caching issue... But if you have any more info that could be useful, please add any potential differences on the pages where it happens and where it does not...

**Comment by lanthonyneville** [comment]
> Looked at this a bit with @mitchelsellers and we could no longer reproduce on the same instance where it was happening... It may be a caching issue... But if you have any more info that could be useful, please add any potential differences on the pages where it happens and where it does not...

I have been trying to find a reliable way to reproduce and not reproduce the issue. However for me, this issue is now happening on every page I edit. There were a few times yesterday when I was in edit mode and did not get duplicate buttons, but now I am consistently getting duplicates. If I find out more I will let you know.

BTW, looking at the HTML, the markup for each button in a pair is identical, and they both function.

**Comment by valadas** [comment]
Hmm, that is odd. Have you tried simply clearing cache and restarting just to rule out maybe a bad cache state or some such...

**Comment by valadas** [comment]
Ok, I just had this happen to me. In my case it was:

1. Add a module on a page
2. Some modules in some cases show their content before the user has a chance to drag it into a pane (very intermittently happens)
3. Reloaded the page to redo it.
4. Boom, duplicate buttons.
5. Restarted the site and it was back to normal.

Can you try restarting the site to see if it fixes the issue ?

**Comment by lanthonyneville** [comment]
I guess it must be a caching issue, because today (after w3wp.exe shut down overnight) I cannot recreate the issue.

I tried your steps above. I am also seeing most module types showing content alongside the square drag/drop box. However, I do not get duplicate buttons.

Do you want to keep this issue open? I'll open another issue about the modules showing content during drag/drop unless its logged already.

**Comment by bdukes** [comment]
We did recently change [`EditBarModule`](https://github.com/dnnsoftware/Dnn.Platform/blob/d7f7bcc53b9b89d091467b47874053e5fa158c76/Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/HttpModules/EditBarModule.cs), the HTTP Module which injects the edit bar.  Could that have anything to do with it?  What would happen if there were two edit bars injected?  Maybe see if you can add some debugging in there and notice if the listener is registered multiple times or something.

**Comment by mitchelsellers** [comment]
@bdukes How long ago was that?

I've recreated this on a 9.3.2 site, so I don't think that is the cause.

**Comment by bdukes** [comment]
I believe that change was in 9.8.0.  It seems like people are seeing it a lot more in 9.8.0 than previously, so maybe it's always been an issue but it's happening more often because of some change in 9.8.0?

**Comment by valadas** [comment]
@lanthonyneville yes, let's leave this issue open, if anyone finds any clue to accurately make it happen, it will be super useful to be able to find this issue and add details...

**Comment by donker** [comment]
The way this works is that whenever the edit bar opens for the first time, DNN looks in the entire installation for a particular type (corresponding to an item on the bar). The result gets cached and rendered to screen. So IMO it can only be because:

1. There is a caching issue. Clearing the cache should resolve this.
2. There is another (old) dll hanging around that adds these buttons as well. Maybe when we reorganized the code and reduced the number of projects resulted in a few users not having an old dll deleted.

**Comment by TopCat6** [comment]
I have a site where this happened all the time. Clearing Cache did not fix the problem.  Restarting the application **did** fix it. So far, can't figure out how to make it happen. Tried @valadas sequence but did not happen.  DNN 9.8.0

**Comment by valadas** [comment]
I was my experience too, intermittent and hard to reproduce (only happened to me once). And a site restart resolves it... Not sure where to start with this. If anyone finds out more, please keep adding comments...

**Comment by zyhfish** [comment]
one possible reason(not 100% sure because no way to reproduce):
https://github.com/dnnsoftware/Dnn.Platform/blob/f4f5c71056d52ef601c561135b3a6a7517b38605/DNN%20Platform/Library/Framework/Reflections/TypeLocator.cs#L52

when the exception is thrown, the Types collection from the exception variable maybe contains types already added, then will cause a duplicate issue.

**Comment by TopCat6** [comment]
I have just noticed a strange quirk in the process, which I have repeated several times on different pages and different sites to confirm. On sites where this occurs, prior to it happening I have noticed that when clicking on the pencil icon to get into page edit mode, the first click does not seem to register. So, of course, one clicks again. Then editing a module and cancelling out of it, I notice that there are the duplicated sets of buttons. This condition carries on when moving to other pages and editing them.
Once I restart the application through the menu, the condition stops and I cannot seem to force it to happen again.

**Comment by jeremy-farrance** [comment]
I don't know if this helps or provides a clue, but here is a reliable way to fix it once it happens.

First, go to PB/Setting, Scheduler and make sure the task scheduler is started. If not, start it. Then switch to Task Queue and wait until any running things catch-up. Then check history and make sure Succeeded is checked for all the recent stuff. (If you can't start the scheduler or your tasks are throwing errors, stop and go investigate that.)

Go to PB/Setting, Scheduler and in the Scheduler tab find Purge Module Cache and click Run Now. Then PB/Settings/Servers and Restart Application. Wait until its full reloaded and the editBar double buttons are gone. So if I am right, that proves that got double generated and written in to the module cache? Which probably doesn't help much.
 
I have noticed that a common way to get the editBar double buttons is remove old modules or libraries in PB/Settings/Extensions.

**Comment by sleupold** [comment]
I haven't seen this behaviour in DNN 9.9.0 yet, can you confirm, this being fixed?

**Comment by TopCat6** [comment]
I too have not seen this behaviour in DNN 9.9.0 as yet. I have had the first click of the edit mode pencil seem to do nothing, but I cannot reproduce it on command. The double toolbar button set seems to no longer occur.

**Comment by valadas** [comment]
I saw it once on 9.9.0 but not a clean site, a very very old upgrade. It only happened once, a restart fixed it and I still don't know how to make it happen because doing exactly the same thing after restart, did not make it happen.

I happened after inserting a recently installed MVC module, that's all I know so far...

**Comment by moorecreative** [comment]
I  had it happen for a site that was upgraded from 9x up to 9.10.2, so it still can occur.
- this instance had three or triplicate... three edit, three close, etc.
- restart did fix the issue (clear cache alone did not)

**Comment by mitchelsellers** [comment]
This appears to be directly related to adding a MVC based module to a page

**Comment by valadas** [comment]
Yeah, I was going to say the same thing, I don't have much MVC modules so this does not happen very often to me, but where I saw it happen, there was almost always some MVC modules installed.

**Comment by Saeedalhs** [comment]
I've upgraded from DNN744 to DNN932 to DNN990 and there was no problem by this issue. When I removed Teleric dependencies base on the guide provided at address below, this issue has been happened. Every action duplicates the 3 buttons to even 20+ ones, fortunately every button works!
[](https://docs.dnncommunity.org/content/getting-started/setup/telerik-removal/index.html )
