### ISSUE TITLE
Allow Webp format 

### ISSUE THREAD

**Issue by uzmannazari** [dnnsoftware/Dnn.Platform#5360]
WebP is a modern image format  and and DNN does not support it in its site settings.

Its not possible to upload webp image format on the Logo option at site settings.

**Comment by WillStrohl** [comment]
First, this could definitely work as a new feature, but you can already do this today if you want..   

It's not possible out-of-the-box, but it is possible after a tiny bit of configuration.  All you need to do is:  

1. [Allow the file extension in the global allow list](https://www.youtube.com/watch?v=WRfXFZflZBw&list=PLojRGd54eWTiK-0y8o5EBYVcCY2yzhTZk&index=19).  
2. [Update the `web.config`](https://www.youtube.com/watch?v=uxkuoBTQBpk&list=PLojRGd54eWTiK-0y8o5EBYVcCY2yzhTZk&index=15) to allow this kind of file to be properly served.  

**Example Snippet from an Existing web.config**  
```xml  
<system.webServer>
  <staticContent>
    <clientCache cacheControlCustom="public" cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00" />
    <remove fileExtension=".webp" />
    <mimeMap fileExtension=".webp" mimeType="image/webp" />
    <remove fileExtension=".svg" />
    <mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
    <remove fileExtension=".woff" />
    <mimeMap fileExtension=".woff" mimeType="font/x-woff" />
    <remove fileExtension=".woff2" />
    <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
  </staticContent>
```

**Comment by uzmannazari** [comment]
hi @WillStrohl 
first, i wrote the format type on global allow list

![image](https://user-images.githubusercontent.com/52697118/198549309-5fb0fec1-5863-405c-afc0-b7b38ce42fa0.png)
then i edited the web.config as you said 

![image](https://user-images.githubusercontent.com/52697118/198550123-6644d0a0-5999-44a2-80bb-eb703673fe08.png)

then recycle the app pool and clear the cache but the file format is not at supported format list of the upload logo windows
![image](https://user-images.githubusercontent.com/52697118/198550581-40f4400a-e3b0-4497-8775-70125636002c.png)


but at upload image windows

**Comment by WillStrohl** [comment]
Oh, well the upload dialog is a completely separate thing.  That might need to be updated differently, depending on where it is and what it does.  

You'll need to update your original post here to be more fully detailed on where in the website you're going and what you're trying to update. The list of files that appears in the Windows dialog is not directly related to the allowable files at this point the use case.  It comes into play after the Windows dialog allows you to choose one or more files.  

So, please update your post's original description to include the exact steps to reproduce the issue you'd like to see resolved.  

Thank you!  :)

**Comment by WillStrohl** [comment]
I'm sorry you're upset, but if you want something fixed in any open source project, the path is pretty consistent across major projects.  The template you deleted to write your original post would have the greatest chance of getting this looked at by anyone else. The exact `Steps to Reproduce` are always required, because the way you do something is not necessarily the way someone else might do it.  

If you don't want to do that, this is fine.  I'm just letting you know that you'll have a better chance of getting more help.  It's up to you.  You don't have to do anything you don't want to do.  🤷🏽‍♂️

**Comment by bdukes** [comment]
- [ ] Global Whitelist for allowed file types - Ensure that it doesn't get duplicated
- [ ] Only Images whitelist (Site Settings -> Site Behavior -> More) - Same as above
- [ ] Web.config must be updated for clean installations to include the proper MIME type
- [ ] Web.config must be updated for upgrade installations to include the proper MIME type, which needs to avoid a collision.
- [ ] Image upload component(s) need to accept webp files (see #5365)

**Comment by jeremy-farrance** [comment]
Adding WEBP to DNN as a standard option still feels needed and necessary. Just to bring topic up to date, correct a few mistakes in the details above, and provide a video demonstrating the problem...

After a default DNN install:

1. In web.config, add or ensure you have `webp` mime mapped (see Will's example above)

2. Allow the "webp" file extension in Settings / Security for both `Allowable File Extensions` and `Default End User Extension Whitelist`:
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/653301/7dd96733-7466-4225-95e2-da1bcc7fe57c)

3. In Site Settings, Site Behavior tab, MORE, change the Whitelist for end users to Custom, then add "webp" to the `Allowed File Extensions`
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/653301/bb9ef746-91e6-4ac8-bf35-bdfd545797eb)


Now, as you can see, even though uzmannazari didn't have enough information for us to reproduce the problem, here is a video demo that clearly shows that the PersonaBar's Site Settings panel is not using DNN's settings for the allowed image formats.
 
Wrong Format Error (appears for about 1 second) after selecting the WEBP file and clicking the Open button.
https://accuraty-my.sharepoint.com/:v:/p/jfarrance/ERvPYc2TntRBmcsZr7NaNv4Bm6GkDeiTr6IP41t0_9yvYQ?e=ReKzSV


### My guess was Dnn.React.Common's FileUpload component was the problem and had the allowed file extension hard-coded:

[https://github.com/dnnsoftware/Dnn.Platform/blob/develop/Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/FileUpload/Browse/index.jsx](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/FileUpload/Browse/index.jsx)

As you can see, they ARE hard coded. **But DO include "webp"**, see line 99-132.

So anyhow, accurate and tested details, a video that makes the problem easy to understand and reproduce. I hope this gets some attention in time for DNN v10.

**Comment by jeremy-farrance** [comment]
I just tested this again on DNN 9.13.09 and its still broken (see VIDEO above).

**Comment by mitchelsellers** [comment]
Just updating this a bit, it appears that the web.config support as noted above was added in 9.06.02 (https://github.com/dnnsoftware/Dnn.Platform/blob/9c01f62d7c436aef3d2cce6371bbca5bedb644f1/DNN%20Platform/Website/Install/Config/09.06.02.config#L9)

**Comment by trouble2** [comment]
Just tried this in DNN 10.3.3.
It looks like I can add the extension in the allowed extensions list.
Then I can upload it using the filemanager.
But I cannot see/select it in CKeditor.
When I try to upload it through the ckeditor it still says: 
"De toegestane bestandstypes zijn: "bmp,gif,jpeg,jpg,png,svg"
(Allowed filetypes are....)
So this appears to be hardcoded.
I know in the past this was a seperate entry in the Dnn.CKEditorSettings.xml but it is not anymore
(see: https://github.com/w8tcha/dnnckeditor/blob/master/CKEditorDefaultSettings.xml)

**Comment by bdukes** [comment]
Here are some places where image extensions are hardcoded in DNN:

- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs#L69
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Modules/Journal/ServicesController.cs#L45
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Modules/Journal/FileUploadController.cs#L29
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Library/Services/UserProfile/UserProfilePicHandler.cs#L23
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Library/Services/GeneratedImage/DnnImageHandler.cs#L540
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Library/Services/GeneratedImage/StartTransform/SecureFileTransform.cs#L22
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Library/Services/GeneratedImage/StartTransform/UserProfilePicTransform.cs#L22
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/basicSettings/index.jsx#L245
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageDetails/PageIcons/PageIcons.jsx#L34
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Website/Resources/Shared/components/FileUpload/dnn.FileUpload.js#L419

And some default lists that may be able to be overridden by an admin:
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Website/Install/DotNetNuke.install.config.resources#L45
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Library/Common/Globals.cs#L436
- https://github.com/dnnsoftware/Dnn.Platform/blob/695f4fc89a262f965a9d8742f49ef6693bde363b/DNN%20Platform/Website/Resources/Shared/components/FileUpload/dnn.FileUpload.js#L590

There are probably others. With the image processing components, we may be able to use https://www.nuget.org/packages/System.Drawing.Common to add support for more formats.

**Comment by uzmannazari** [comment]
I think the main problem is not WebP itself, but the fact that supported image extensions are hard-coded in several different places.

Instead of adding `webp` to every hard-coded list, DNN should have a single source of truth for supported image formats.

For example:

```csharp
public interface IImageExtensionProvider
{
    IReadOnlyCollection<string> GetSupportedExtensions();
    bool IsSupported(string extension);
}
```

Then Site Settings, CKEditor, Journal, profile pictures, page icons, file upload components, etc. should all use the same centralized list.

Also, `AllowedFileExtensions` and `SupportedImageExtensions` should be separate concepts:

* `AllowedFileExtensions`: security/upload whitelist
* `SupportedImageExtensions`: formats DNN treats as images

Client-side components should receive the supported image extensions from the backend instead of keeping their own hard-coded arrays.

This would fix the current inconsistency and prevent the same issue from happening again when new image formats are added in the future.
